### ISSUE TITLE
Management Portal - Git notification

### ISSUE THREAD

**Issue by jbglytec** [intersystems/git-source-control#249] opened 2023-03-01 20:24 UTC
As an end-user when making changes to a production via the management portal
We would like to see some indication that a file has been checked out and changed needing to be committed from the UI
So that we do not leave the namespace without committing and pushing changes leaving the namespace in a read-only state.

**Comment by isc-bspead** [comment] 2023-03-01 21:36
@jbglytec - I may be mistaken but I believe that we're limited to the features of the management portal for this once, and how it behaves when server-side source control is configured (so the issue isn't restricted to just users of git-source-control).  But I will wait for others to weigh in as well on this.

**Comment by isc-tleavitt** [comment] 2023-05-18 13:23
I've reported an upstream issue for IRIS (internal reference: DP-422984) that would cover this entirely. That is, if implemented at the IRIS level, git-source-control and other embedded source control implementations like it would have such indicators added everywhere relevant automatically.

**Comment by isc-tleavitt** [comment] 2023-05-18 13:29
Closing this given that no further work is needed/possible on the git-source-control side. (But if I see changes coming at the product level I'll let you know!)

**Closed by isc-tleavitt** 2023-05-18 13:29 UTC
Labels: upstream
