### ISSUE TITLE
Studio: hanging on Git operations, Git menu very slow to load

### ISSUE THREAD

**Issue by zdateh** [intersystems/git-source-control#269] opened 2023-07-28 12:35 UTC
I am unable to practically use the Git menu in studio - doing operations like 'Fetch from Remote' just hangs Studio, with no error or anything in the console. Are there any ways I can diagnose what is causing this?

The Git menu is also slow to load - it takes around 5 seconds to display, which makes it pretty hard/annoying to use whilst working. I also fancy this extension has slowed down Studio in general.

By using a combination of what works and Git bash, I can do change control, but not really ideal!

**Comment by isc-tleavitt** [comment] 2023-07-28 12:36
@zdateh are you set up with an https remote? This sounds like https://github.com/intersystems/git-source-control/issues/235.

**Comment by zdateh** [comment] 2023-07-28 13:26
@isc-tleavitt Hi, yes we're using an https remote (Azure dev ops). Would ssh remotes potentially help (that's the other option provided in Azure)?

re: #235 I haven't seen any credential checks coming up

**Comment by isc-tleavitt** [comment] 2023-07-28 13:27
@zdateh yes, switching to ssh would fix the issue.

The problem is that the credential check is coming up in the background and hanging the process on the server. :(

**Comment by isc-tleavitt** [comment] 2023-07-28 13:28
Closing this as a duplicate of #235

**Comment by zdateh** [comment] 2023-07-31 14:01
Switching to SSH has indeed fixed my remotes issue - all git operations appear to succeed so far, thanks!

However it's still as slow in studio as before :( I am unsure what it could be doing in the background as git operations are near-instant from the command line, but as soon as I click on that Git menu, it's doing nothing for 5 seconds. Any ideas?

**Comment by zdateh** [comment] 2023-11-27 11:55
Hi, could we please re-open this? We have been using SSH as requested but the menus and studio operation is still noticeably slower with Git extension active. e.g.:

- re-opening/closing studio with many routines/classes being edited takes over a minute.
- loading a routine/class takes 5-10 seconds

None of them dealbreakers but can be annoying whilst developing :)

Cheers

**Comment by isc-tleavitt** [comment] 2023-11-27 14:04
@zdateh sure, happy to reopen given your observations.

Technically speaking (for whoever picks this up):
We run "git status" to see what's currently pending. There's some caching of the results built-in for rendering the menus (so that we don't re-run for each menu item), but not across operations (e.g., loading multiple tabs with different files in Studio). Load of a single class/routine taking 5-10 seconds is particularly unexpected.

@zdateh - if you could capture %SYS.MONLBL (RtnLine/Time/TotalTime) on SourceControl.Git.* and attach as CSV that would be super helpful.

**Comment by zdateh** [comment] 2023-11-27 18:43
Thanks! Attached csv:
[zcjb_sourcecontrol.csv](https://github.com/intersystems/git-source-control/files/13479015/zcjb_sourcecontrol.csv)

**Comment by isc-tleavitt** [comment] 2023-12-05 19:34
@zdateh thank you, that's super helpful - the bottleneck isn't at all where I would have expected. (Which is why %SYS.MONLBL is so great.)

Top issues are:

Routine | Line | RtnLine | Time | TotalTime | Code
SourceControl.Git.Extension.1 | 41 | 3 | 0.000023 | 7.5793 | do ##class(SourceControl.Git.Change).RefreshUncommitted(,,.files)
SourceControl.Git.Change.1 | 1042 | 6820 | 0.007226 | 7.011443 | set InternalName =   ##class(SourceControl.Git.Utils).NameToInternalName(filename,0,0)
SourceControl.Git.Utils.1 | 989 | 6832 | 0.04499 | 5.520985 | set   sc=$system.OBJ.Load(Name,"-d",,.outName,1)
SourceControl.Git.Utils.1 | 1459 | 13694 | 0.012658 | 1.299256 | If   ##class(%Library.RoutineMgr).UserType(InternalName,.docclass,.doctype) {

We can definitely optimize these things.

**Comment by isc-tleavitt** [comment] 2024-01-26 18:02
This is fixed via #318.

**Closed by isc-tleavitt** 2024-01-26 18:02 UTC
Labels: bug, customer
