### ISSUE TITLE
ZPM Inconsistencies 

### ISSUE THREAD

**Issue by michael-rust** [intersystems/git-source-control#470] opened 2024-09-06 18:25 UTC
ZPM functionality is inconsistent in different namespaces on the same IRIS instance. See screenshots attached. 
1. In the IRTUS namespace the zpm command works and we can run the "install git-source-control" command
2. In the RUST namespace zpm works but we can error when running the "install git-source-control" command
3. In the KANIA namespace the zpm command is not recognized.

[ZPM inconsistencies.docx](https://github.com/user-attachments/files/16911760/ZPM.inconsistencies.docx)

---

TSL notes: keeping this open to track last remaining upstream issue, which presents as not being able to compile classes from lite terminal (and therefore zpm "install git-source-control" not totally working and possibly leaving things in a broken state).

**Comment by isc-tleavitt** [comment] 2024-09-06 18:29
@michael-rust this seems like more of an IPM issue, and it's quite an interesting one. There's a really good chance this is related to the errors you've reported in #467. Let's set up some time to discuss next week - I'll reach out through alternative channels.

**Comment by michael-rust** [comment] 2024-09-06 18:31
Thanks, Tim.

**Comment by isc-tleavitt** [comment] 2024-09-06 18:52
Ohhh... I'm remembering now that you guys are running IPM 0.9.0 because of some issue that had only been fixed there; I think it was https://github.com/intersystems/ipm/issues/440. We have some work in progress to better support enabling IPM instance-wide (https://github.com/intersystems/ipm/pull/485) that I was planning to circle back to next week anyway. That will provide a better/long-term solution to exactly the issues you're seeing.

Let's still meet to talk through the two issues.

**Comment by isc-tleavitt** [comment] 2024-09-10 19:43
Re: RUST namespace example where install fails, solution was:
`zpm "repo -n registry -r -url https://pm.community.intersystems.com"`

Re: KANIA namespace, the issue was somehow related to the lite terminal in VSCode. I'll take this as an action item to investigate.
Fix was `do $system.OBJ.CompilePackage("%IPM")`

There's still some weird SQLCODE -400 going on running some queries somewhere.

**Comment by isc-tleavitt** [comment] 2024-09-10 20:27
SQLCODE -400 was a locking issue ultimately, possibly also related to the lite terminal problems.

**Comment by isc-tleavitt** [comment] 2024-09-10 20:28
Remaining problems here are upstream (lite terminal for VSCode) - will try to dig a bit more as the same issues had bitten me separately.

**Comment by isc-tleavitt** [comment] 2024-10-01 16:52
@isc-etamarch encountered the lite terminal issue yesterday. We did LOG^%ETN at the prompt and somehow were 86 stack levels deep in SQL compilation at the terminal prompt (no debug prompt or other indicators of this state). This is probably the same behavior that @michael-rust and I had encountered, and probably with the same root cause (in all three cases it happened while trying to install git-source-control via IPM).

Attached ^ERRORS from that environment for the day - stack trace is in error #10.

[data_db_mgr_ETAMARCH_export.zip](https://github.com/user-attachments/files/17213157/data_db_mgr_ETAMARCH_export.zip)

$zu(56) indicates an <ENDOFFILE> error which I don't think is the root cause.

**Comment by isc-tleavitt** [comment] 2024-10-02 12:47
Note: can reproduce this at will by purging cached queries for the namespace and then running any zpm command. e.g.:

```
TLEAVITT>zpm "list"
git-source-control 2.5.0
TLEAVITT>w $stack
3
TLEAVITT>d $System.SQL.Purge()

TLEAVITT>w $stack
3
TLEAVITT>zpm "list"

TLEAVITT>w $stack
40
```

**Comment by isc-tleavitt** [comment] 2024-10-02 13:06
Upstream Jira filed with details: DP-435099

I'm going to close this out as there's nothing more to do on the git-source-control end.

**Closed by isc-tleavitt** 2024-10-02 13:06 UTC
Labels: upstream, customer
