### ISSUE TITLE
Output of Schema with periods (dots) in name breaks SC Ad

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#130] opened 2022-02-17 18:57 UTC
(latest commit testing)

When adding a Schema to source control (SC Menu->Add), receive error in browser:

![image](https://user-images.githubusercontent.com/65192819/154551136-dce93298-6965-4fb2-9e77-ec992bdd5fb3.png)

Looking in WebUI afterwards, I can see it partially worked but clearly does not like the dots - note if I click either of the items in this screenshot, I see nothing.

![image](https://user-images.githubusercontent.com/65192819/154551282-c8e639cf-00df-4be5-9b68-488895274f83.png)

Maybe has something to do with the output pathing I desire to use (which you can see on 2nd screenshot.)

**Comment by CraigRegester** [comment] 2022-02-17 19:21
So that's the 2nd part of the issue then but seems like the first part (where it's referencing the new global for tracking) is different and also out it outputs on the filesystem... it's creating folders w/ the dots still.

Output in the filesystem:

```shell
In_Cdi_Rslt_2/3:
total 8
drwxrwsr-x    2 cacheusr gitusers        256 Feb 17 13:50 .
drwxrwsr-x    3 cacheusr gitusers        256 Feb 17 13:50 ..
-rwxrw-r--    1 cacheusr gitusers        339 Feb 17 13:50 1.hl7
```

**Comment by isc-svelury** [comment] 2022-02-17 19:58
From my understanding it looks like the file isn't being exported as expected and so the` InternalName` is coming up as an empty string. I think that's where we get the subscript error is from. 

How are your mappings configured? I am not able replicate the issue. I switched the mapping to `.inc` files to NoFolders and adding and removing from source control seems to work as expected for me. The flat folder structure is maintained even when I add multiple `.inc` files from different packages.

**Comment by CraigRegester** [comment] 2022-02-17 20:48
Yea so if I turn on 'NoFolders', it "works" to a degree (though I still got the subscript error):

![image](https://user-images.githubusercontent.com/65192819/154566816-1b77c580-1f3e-46c0-b1e4-b38f8095f0c3.png)
![image](https://user-images.githubusercontent.com/65192819/154566878-6ec86819-3909-4220-a0e0-6882fe0bd7f3.png)

Wonder if I need to flush out git-source-control and reload (as I tried to just load the latest repo code using zpm without purging out the previous stuff... so did it initialize anything you need to track the globals properly after switching from sclist?

It does output "right" filename wise with NoFolders

```shell
cacheusr@oairsint1:/hfs/sys/git/IRISHealth/hl7$ ll
total 16
drwxrwsr-x    3 cacheusr gitusers        256 Feb 17 15:39 .
drwxrwsr-x    6 cacheusr gitusers        256 Feb 17 13:40 ..
-rwxrw-r--    1 cacheusr gitusers        640 Feb 17 15:36 HealthShare_2.5.hl7
-rwxrw-r--    1 cacheusr gitusers        400 Feb 17 15:39 In_Ep2_Rslt_2.5.1.hl7
```

Though it's not foldering where I need it to address the multiple namespace factor so I may need to dig in a bit there with a fork to see if I can get it to respect similar foldering that works in other areas (e.g., DTLs, CLS, etc.)

![image](https://user-images.githubusercontent.com/65192819/154567685-5d8412d5-6ef0-4036-870f-8484bf05fa0d.png)

(INTGBUS being an example of the namespace 'folder') Gonna try to flush out what zpm currently has installed/loaded and start fresh first.

**Comment by isc-tleavitt** [comment] 2022-02-17 20:51
Really the issue here is in the settings UI - you can still define a folder with "NoFolders" (which is re: the dot behavior in the filename).

**Comment by isc-tleavitt** [comment] 2022-02-17 20:57
Workaround re: file/folder naming will be:
```
set ^SYS("SourceControl","Git","settings","mappings","HL7","*")="INGTBUS/hl7/"
set ^SYS("SourceControl","Git","settings","mappings","HL7","*","NoFolders")=1
```
Still need to sort out the <SUBSCRIPT> error via defensive coding and testing with HL7 schemas specifically to see if (perhaps) the %Studio.AbstractDocument type is throwing things off.

**Comment by CraigRegester** [comment] 2022-02-17 20:59
Ah interesting, so you're saying it should be blocking me out of that last column when I enable NoFolders, gotcha. Yea wondered why that was but was foggy on the idea of 'NoFolders' so wasnt sure.

**Comment by CraigRegester** [comment] 2022-02-18 17:08
Turned off SC in MP, flushed out git-source-control and re-loaded latest code. All re-initialized (also reset my git folder and set it back up - completely clean) Still seeing this when doing an 'Add'... *

![image](https://user-images.githubusercontent.com/65192819/154729364-0d8da063-151c-4c61-83a2-fff5c42d6303.png)

But! Using @isc-tleavitt workaround above, the file does output right now!

![image](https://user-images.githubusercontent.com/65192819/154729607-f0a6b847-d2e3-414b-84e4-603be6c35b23.png)

**Comment by CraigRegester** [comment] 2022-02-22 23:01
Are you guys able to reproduce what I'm seeing with the Add command inside MP for LUTs/Schemas? 

Wasn't sure if this was specifically happening just to me or a known bug. I see @isc-svelury mentioned it looked like it wasn't getting the item name which I concur. 

Will dig more tmrw myself.

**Comment by isc-svelury** [comment] 2022-02-23 14:56
I haven't gotten around to reproducing it yet. I'll keep you posted.

**Comment by CraigRegester** [comment] 2022-02-24 16:02
> I haven't gotten around to reproducing it yet. I'll keep you posted.

No worries, just making sure I didnt need to provide more info! Sounds like you guys figured it out though so I'll stop digging. Ty both!

**Comment by isc-svelury** [comment] 2022-03-11 21:35
@CraigRegester as an update, I replicated the issue you were seeing. You were seeing a subscript error because `NameToInternalName()` returns an empty string for files that aren't in a typical export format even if there are mappings for that file type. This is the specific snippet: https://github.com/intersystems/git-source-control/blob/9068eb3619b0a002b4476eaa35c081e97fedd690/cls/SourceControl/Git/Utils.cls#L1558-L1566)

I have fixed the issue and also fixed the mappings in the settings page. I still have a loose ends to wrap up and then I'll send a PR to close this issue.

**Comment by CraigRegester** [comment] 2022-03-11 21:37
Wonderful! ty for the update, Glad you were able to reproduce. I haven't had time to dig in myself yet. Once PR is done, I'll pull latest commits again and retest. Excited to get using it!

**Comment by CraigRegester** [comment] 2022-03-21 14:36
Just a heads up, this issue (or the original related one that led to NoFolders) impacts the VS Code objectscript extension as well.

When using non-ISFS mode and choosing to export an HL7 schema with dots in the name (even the base schemas are like this), the dots are converted to slashes/folders on export. 

Wonder if any of the efforts you guys are making here can help address it over there as well.

**Comment by isc-tleavitt** [comment] 2022-03-21 14:42
@CraigRegester ultimately the two issues are disconnected; we'll need a separate solution in VSCode export. Do you have a related VSCode issue?

**Comment by CraigRegester** [comment] 2022-03-21 14:44
I do not but can open one. Just wasn't sure how connected your group was to the VSCode one. No worries!

**Comment by isc-tleavitt** [comment] 2022-03-21 14:45
Not super connected, but we know who to pester and I've occasionally contributed to the vscode extension. ;)

**Closed** 2022-03-22 20:17 UTC
Labels: bug

**Comment by CraigRegester** [comment] 2022-03-29 13:28
Pulled latest commits and re-tested... I still get this when I go to Lookup Tables and try to add a table with the source control menu:

![image](https://user-images.githubusercontent.com/65192819/160621865-2ada3045-cf9e-4488-a72b-942f4ed640c4.png)

However, when I look in the output, it seems to at least partially be working now? Maybe more I can check to help figure out what's causing the pop up error?

![image](https://user-images.githubusercontent.com/65192819/160622069-f78eae5f-e141-465d-b2fb-d84a6ec8f875.png)

**Comment by CraigRegester** [comment] 2022-03-29 13:29
See this in the Git GUI

![image](https://user-images.githubusercontent.com/65192819/160622258-fd1ac038-bed2-4ea7-8d64-2df2f5b352c0.png)
![image](https://user-images.githubusercontent.com/65192819/160622291-62110d27-37f2-4578-8195-885cd7c3b66d.png)

**Comment by isc-svelury** [comment] 2022-03-29 13:43
How are your mappings set up? Could you add a screenshot of the output from `zw ^SYS("SourceControl","Git","settings","mappings")`?

The 'Could not access' error is happening because the highlighted entry is a directory. It's simple to expand the directory and list its files. I opened #175 for it. I'll send a PR against that.

**Comment by isc-svelury** [comment] 2022-03-29 15:32
I tried to replicate this error and I did see something similar when the LUT file I created wasn't saved before adding to source control. In that case, the export of the item failed because the file did not exist. 

Can you try:
```
set sc=##class(SourceControl.Git.Utils).ExportItem("<filename>", ,1,.filenames)
w $System.Status.GetErrorText(sc)
```

If it's the same issue you should see something like `ERROR #16005: Document '<filename>' does NOT exist`

**Comment by CraigRegester** [comment] 2022-03-29 15:50
Additional interesting note... this command on an existing table that was not yet present in the Global tracker:

```
DEV:cacheusr:INTGBUS>set sc=##class(SourceControl.Git.Utils).ExportItem("TestTable2.lut", ,1,.filenames)
exporting new version of TestTable2.lut to /hfs/sys/git/ISC-IRISHealth/INTGBUS/src/oth/TestTable2.lut
```

It created a global entry for TSH (timestamp of last compile) but not one for items...

`
zw ^SYS("SourceControl","Git","items","TestTable.lut")
^SYS("SourceControl","Git","items","TestTable.lut")=""
zw ^SYS("SourceControl","Git","TSH","TestTable.lut")
^SYS("SourceControl","Git","TSH","TestTable.lut")="66197,41839"
^-- Good
zw ^SYS("SourceControl","Git","TSH","TestTable2.lut")
^SYS("SourceControl","Git","TSH","TestTable2.lut")="66197,41861"
zw ^SYS("SourceControl","Git","items","TestTable2.lut")

^--- missing?
`

**Comment by isc-svelury** [comment] 2022-03-29 16:06
So to explain my reasoning for checking if the export works as expected is that the `filenames` variable is updated while exporting an item. It's mainly used for complex items like packages that can have multiple sub-items associated with them. If we are adding a single file, `filenames` should have a node corresponding to that file after export. 

@isc-tleavitt do you know why filenames might be undefined if export works as expected?

**Comment by isc-tleavitt** [comment] 2022-03-29 16:35
@CraigRegester are you sure you have the latest commits loaded?

Would be interested to know if SourceControl.Git.Utils:AddToSourceControl calls ExportItem with the 3rd arg set to 1. (Not doing so could explain the issue - I was going to comment saying so based on the older version I have installed but see that it has changed.)

**Comment by CraigRegester** [comment] 2022-03-29 16:46
Will double check that particular example but yes, cloned into a fresh directory yesterday and did a load using zpm

**Comment by CraigRegester** [comment] 2022-03-29 17:27
@isc-tleavitt You are correct that the method is out of date.... but why? If I look at the package I cloned yesterday, it _is_ correct... has the 1 in the third parameter. So why when I did a zpm load from that directory did it not refresh all the classes?

Is there a parameter I need to toss on the zpm load?

**Comment by isc-tleavitt** [comment] 2022-03-29 17:31
@CraigRegester it should just be zpm "load /path/to/where/you/cloned" - maybe you picked the wrong directory?

**Comment by CraigRegester** [comment] 2022-03-29 17:50
That's what it was - ugh, sorry, embarrassed. I blame my novice use of ZPM

Will retest now

**Comment by isc-tleavitt** [comment] 2022-03-29 17:53
@CraigRegester an understandable misunderstanding - some packages do set up a %ALL mapping. I personally don't like doing that because it's a bit more invasive than necessary, but perhaps it would make sense to do that with git-source-control - or at least offering the option to do so.

**Comment by CraigRegester** [comment] 2022-03-29 17:56
No problem - I have no strong opinion other than maybe a call out when pulling down new versions to be sure to do it in the proper namespace and/or each namespace (if multiple namespaces on that instance.)

Definitely working better now! Only weird thing that popped up on me is after adding a table, I asked it to discard changes and got this:

![image](https://user-images.githubusercontent.com/65192819/160674984-5c111630-ed91-41d5-9fb8-603bcde0ecb8.png)

But that may still be a work in progress.

**Comment by isc-svelury** [comment] 2022-03-29 18:06
I see that too. I think we're seeing this error because the method used to load files does support loading .lut files. I think we will need to export the file out as an XML file and it should work. I created an issue for that: #176
